# Generated by Django 5.1.7 on 2025-07-18 07:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='document',
            name='title',
        ),
        migrations.RemoveField(
            model_name='document',
            name='updated',
        ),
        migrations.AddField(
            model_name='document',
            name='doc_id',
            field=models.CharField(default='default_doc_id', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
