# Generated by Django 5.1.7 on 2025-07-24 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('editor', '0002_remove_document_title_remove_document_updated_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='title',
            field=models.CharField(default='Untitled', max_length=255, unique=True),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='document',
            name='content',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='document',
            name='doc_id',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
